### ISSUE TITLE
Error when clicking Next Turn

### ISSUE THREAD

**Issue by Damuth1977** [Nevela-0/PF1-Improved-Conditions#6]
Foundry v11.315 (self-hosted)
PF1e 10.7
Mods active: PF1-Improved-Conditions & Socketlib

Everytime I click next turn in the combat tracker I get a very long error message:

```
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at [Symbol.hasInstance] (<anonymous>)
    at gt (is-binary.js:21:28)
    at mt (is-binary.js:36:9)
    at mt (is-binary.js:45:63)
    at mt (is-binary.js:45:63)
    at mt (is-binary.js:45:63)
    at mt (is-binary.js:45:63)
    at mt (is-binary.js:45:63)
    at mt (is-binary.js:45:63)
    at mt (is-binary.js:45:63)
gt @ is-binary.js:21
mt @ is-binary.js:36
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
mt @ is-binary.js:45
Show 199 more frames
Show lessUnderstand this error
```

**Comment by Nevela-0** [comment]
Should be fixed with v1.2
